name: Lint Check
run-name: Github Actions Lint

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout github repo
        uses: actions/checkout@v4
